# Generated by Django 5.0.6 on 2024-05-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='feedback',
        ),
        migrations.AddField(
            model_name='feedback',
            name='descrizione',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Descrizione'),
        ),
    ]
